version: '3.1'

services:
  healthdashboard:
    build:
      context: .
    links:
      - 'mongodb'
    ports:
      - '5000:8000'
    environment:
      - USER='animesh'
      - PASS = 'marlowe'
  mongodb:
    image: mongo:latest
    container_name: "mongodb"
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - /var/lib/mongodb:/data/db
    ports:
      - "27017:27017"
